soccer_calendar_team_calendar:
    path: /{competitionName}/team/{teamName}.ics
    controller: Endroid\SoccerCalendarBundle\Controller\TeamCalendarController

soccer_calendar_team_list:
    path: /
    controller: Endroid\SoccerCalendarBundle\Controller\TeamListController
