services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Endroid\SoccerCalendarBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Endroid\SoccerCalendar\Factory\CalendarFactory:
        public: true

    Endroid\SoccerData\Sofascore\Loader\TeamLoader: ~
    Endroid\SoccerData\Loader\TeamLoaderInterface: '@Endroid\SoccerData\Sofascore\Loader\TeamLoader'

    Endroid\Calendar\Writer\IcalWriter: ~
